# .github/workflows/c-cpp.yml

name: C/C++ CI

# 1. WHEN TO RUN: Define triggers
on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]

# 2. WHERE TO RUN: Define the jobs
jobs:
  build-and-test:
    # Use the latest stable Ubuntu runner environment
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Step 2: Install necessary compiler and tools
      # Note: Ubuntu runners often have GCC/G++ and CMake pre-installed,
      # but it's good practice to ensure specific versions or tools.
      
      # Step 3: Configure the build using CMake
      - name: Configure CMake Build
        run: cmake -B ${{github.workspace}}/build
        # -B specifies the build directory (e.g., 'build')

      # Step 4: Compile the code
      - name: Build Code
        # --build is the command to compile based on the configuration
        run: cmake --build ${{github.workspace}}/build

      # Step 5: Run tests (Assuming you have tests defined in CMake/CTest)
      - name: Run Tests
        # --test is the command to run CTest tests
        run: ctest --test-dir ${{github.workspace}}/build
